### ISSUE TITLE
How to expose vpp init function parameters in forwarder-vpp?

### ISSUE THREAD

**Issue by ljkiraly** [networkservicemesh/cmd-forwarder-vpp#1030]
To twerk some configuraton parameters for AF_PACKET and AF_XDP some parameters should be exposed. The following should be considered:
1/ Add environment variables to container of cmd-forwarder-vpp. There are ten possible parameters.
2/ An other way is to define a configuration file and process the initiation with the given values. An example can be found in PR #1027

Any suggestion is welcome.

**Comment by denis-tingaikin** [comment]
I think we may start with option 2 and provide this file via configmap mounting.

/cc @edwarnicke @glazychev-art
