### ISSUE TITLE
Request for livenessProbe and readinessProbe functionality

### ISSUE THREAD

**Issue by rpiceage** [networkservicemesh/cmd-forwarder-vpp#108]
Please implement some functionality that can be used as livenessProbe and readinessProbe in a helm chart, like the HTTP probes for the old-gen NSM version.

**Comment by denis-tingaikin** [comment]
Hello @rpiceage 

NSMgr and other endpoints using "google.golang.org/grpc/health/grpc_health_v1" server. So please consider using google.golang.org/grpc/health/grpc_health_v1 client to solve the issue.

**Comment by rpiceage** [comment]
Hi @denis-tingaikin 
Thanks for the quick answer and the info. We will look into this.

**Comment by denis-tingaikin** [comment]
@rpiceage Be free to reopen this if the problem will actual :)
