### ISSUE TITLE
CONNECT_TO is not informative and is used incorrectly

### ISSUE THREAD

**Issue by uablrek** [networkservicemesh/cmd-forwarder-vpp#23]
The `CONNECT_TO` variable is used for the NSM URL. It is not informative and should be replaced with something better, e.g "NSM_URL". This goes for all NSM modules where "CONNECT_TO" is used.

In this particular module, as a consequence of the poor naming, CONNECT_TO is incorrectly used to connect to the registry.

https://github.com/networkservicemesh/cmd-forwarder-vpp/blob/1e88454bf3b95072b3be932923aead1b24d3b351/main.go#L175-L185

I use this fix for the problem;

```diff
--- a/main.go
+++ b/main.go
@@ -56,6 +56,7 @@ type Config struct {
        NSName           string        `default:"xconnectns" desc:"Name of Network Service to Register with Registry"`
        TunnelIP         net.IP        `desc:"IP to use for tunnels" split_words:"true"`
        ConnectTo        url.URL       `default:"unix:///connect.to.socket" desc:"url to connect to" split_words:"true"`
+       RegistryURL      url.URL       `default:"tcp://nsm-registry-svc:5002" desc:"url to registry" split_words:"true"`
        MaxTokenLifetime time.Duration `default:"24h" desc:"maximum lifetime of tokens" split_words:"true"`
 }
 
@@ -178,8 +179,9 @@ func main() {
        now = time.Now()
        registryCreds := credentials.NewTLS(tlsconfig.MTLSClientConfig(source, source, tlsconfig.AuthorizeAny()))
        registryCreds = grpcfd.TransportCredentials(registryCreds)
+       logrus.Infof("NSM: Connecting to NSE registry %v", config.RegistryURL.String())
        registryCC, err := grpc.DialContext(ctx,
-               config.ConnectTo.String(),
+               grpcutils.URLToTarget(&config.RegistryURL),
                grpc.WithTransportCredentials(registryCreds),
                grpc.WithBlock(),
        )
```
```
```

**Comment by edwarnicke** [comment]
Hmm... we do want the best possible naming here to provide clarity.   It happens that the Forwarder connects to the same URL for both Registry and NetworkService services...

What was the underlying bug you were seeing?  I don't quite follow.

**Comment by uablrek** [comment]
> It happens that the Forwarder connects to the same URL for both Registry and NetworkService services

Oh, sorry I was mislead by the comment. Closing

**Comment by edwarnicke** [comment]
So... lets talk a bit about *why* you got confused.  You are a bright guy, if you got confused, someone else will... how can we make it clearer?
