### ISSUE TITLE
Add vlan remote mechanism support

### ISSUE THREAD

**Issue by ljkiraly** [networkservicemesh/cmd-forwarder-vpp#358]
The vlan mechanism should contain vlan tag and interface name. The NSE plays a controller role only set the mechanism parameters and provides IPAM.  There is no data plane for the Network Service. The forwarder should contain client processing the remote vlan parameters and "push pop of vlan encap on the wire".
Example sketched by @edwarnicke:

- Say we have the NetworkService 'finance-bridge-domain' being provided by the physical network.

- An NSE can be run on a Pod, registering itself directly (rather than via the NSMGR) for that Network Service.

- When a Client requests the 'finance-bridge-domain', its local NSMGR finds a URL for the Pod of the NSE in the Registry

- The NSMGR sends the Request to the NSE

- The NSE maps the Network Service Name 'finance-bridge-domain' to a vlan tag (say 12) and returns the remote mechanism of type vlan (class remote) with tag 12 as its parameter.

- The NSMgr plumbs in whatever the local mechanism is for the client in such a way it will arrive at the physical network on vlan 12.

Related Issue: [cmd-forwarder-vpp#355](https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/355) Move some generic functions from internal/vppinit to sdk-vpp
Related PRs:

- networkservicemesh/api#112
- networkservicemesh/cmd-forwarder-vpp#365
- networkservicemesh/sdk-vpp#399
- networkservicemesh/sdk-kernel#355
- networkservicemesh/sdk#1093

Sample NSE for reference: https://github.com/Nordix/nsm-nse-generic/tree/vlansup-dev

[Test plan](https://github.com/Nordix/nsm-nse-generic/tree/vlansup-dev/test)

**Comment by ljkiraly** [comment]
Added [test plan](https://github.com/Nordix/nsm-nse-generic/tree/vlansup-dev/test)

**Comment by edwarnicke** [comment]
Got it, you are wanting to cross connect out a physical interface with a vlan.  Question: do you also want to be able to do so via a vfio attached interface?

**Comment by edwarnicke** [comment]
@ljkiraly That diagram helps a lot :)

It might be a good idea to approach this the way we approached the SRIOV problem that is analogous to it.

In Network Service Mesh, we have a concept of a "network service domain".  So your network service can be "bridge-domain@dc1.example.com" where "dc1.example.com" is your "network service domain".

We use this in SRIOV, to associate the SRIOV NIC to a "network service domain" so that we can map logically to interfaces based on the requested network service.

Rather than trying to figure out how to distribute interface names (an implementation detail) all across the system, it might make more sense to do the same thing here.

Looping in @Bolodya1997 here, who did the SRIOV work and would probably be good to talk to :)

**Comment by Bolodya1997** [comment]
> Just a question regarding an implementation detail: Is that right that the interface name to a PCI address is [fetched](https://github.com/networkservicemesh/sdk-sriov/blob/752d65c9889ce04a94893c705dbeb409855f7889/pkg/sriov/pcifunction/function.go#L50) from OS directory structure?

Yes, you are totally right.


> In my qemu/virtio based test environment the network interface name can be find in directory:
> `/sys/bus/pci/devices/<address>/<virtioX>net/`
> instead of `/sys/bus/pci/devices/<address>/net/`

My fault, I didn't expect such behavior :)

I can recommend you to do the following:
1. [`netInterfacesPath`](https://github.com/networkservicemesh/sdk-sriov/blob/752d65c9889ce04a94893c705dbeb409855f7889/pkg/sriov/pcifunction/function.go#L29) is currently set as a constant. You can turn it into a `pcifunction.Function` field and pass it into the `pcifunction.PhysicalFunction` constructor.
I would rather suggest to do it as an option ([options example](https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/chains/client/options.go)) with default value set to `"net"`.
2. `pci.Pool` shouldn't actually know about what exactly should be `netInterfacesPath` for the PCI Function, but it also can have an option to set custom path without any default value.

**Comment by ljkiraly** [comment]
Hi @edwarnicke,
I implemented the "network service domain" to interface mapping and added to the PRs  
I updated the issue description with the links to related PRs.
Please let me know if I can help tying these.

**Comment by edwarnicke** [comment]
@ljkiraly I'll have a look :)

**Comment by denis-tingaikin** [comment]
@edwarnicke, @ljkiraly Have we merged all PRs for this issue? Can we close this?

**Comment by edwarnicke** [comment]
@denis-tingaikin I'm fine with closing this.  @ljkiraly What are your thoughts?

**Comment by ljkiraly** [comment]
The PRs were merged so the issue can be closed.
New issue can be raised for example NSE and test cases.
