### ISSUE TITLE
TestForwarderTestSuite/TestCombinations/Ip/Kernel/Wireguard  is unstable

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/cmd-forwarder-vpp#417]
TestForwarderTestSuite/TestCombinations/Ip/Kernel/Wireguard  is unstable

## Build

https://github.com/networkservicemesh/cmd-forwarder-vpp/runs/4342269191?check_suite_focus=true

**Comment by glazychev-art** [comment]
@NikitaSkrynnik 
we still have `:0` port here: https://github.com/networkservicemesh/cmd-forwarder-vpp/runs/4342269191?check_suite_focus=true#step:5:3674
Could you please take a look?

**Comment by edwarnicke** [comment]
May be related to https://github.com/networkservicemesh/cmd-forwarder-vpp/pull/410

**Comment by denis-tingaikin** [comment]
Fixed by https://github.com/networkservicemesh/cmd-forwarder-vpp/pull/418
