### ISSUE TITLE
Update vpp version

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/cmd-forwarder-vpp#802]
### Description

We need to update VPP to the latest possible version. It must match the version used by Calico-vpp.
(look at https://github.com/projectcalico/vpp-dataplane/commit/d8288e154cfb7d757e039d3a707d67ac4a0c5e49)

**Comment by denis-tingaikin** [comment]
Related to https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/283

**Comment by glazychev-art** [comment]
Prepared a couple of wireguard VPP patches:
https://gerrit.fd.io/r/c/vpp/+/38000
https://gerrit.fd.io/r/c/vpp/+/38001

**Comment by glazychev-art** [comment]
Govpp update:
https://github.com/edwarnicke/govpp/pull/64

**Comment by glazychev-art** [comment]
Updated
