### ISSUE TITLE
Increased memory footprint

### ISSUE THREAD

**Issue by zolug** [networkservicemesh/cmd-forwarder-vpp#841]
When running in AF_PACKET mode there seems to be a memory increase in the NSM supplied VPP process on NSM 1.8.

For me it seems the root cause might be the amount of memory assigned to an af_packet socket.
Previously it was ~20MB per socket while with 1.8 it appears to be 135MB per af_packet socket.

In case multiple interfaces are provided in the device-selector-file for vpp-forwarder, vpp seems to create an af_packet socket for each, which can significantly increase the memory footprint (RssFile) and risk OOM.

Is the increase due to the vpp version update? Are there any known NSM issues that are meant to be fixed by the increased af_packet memory?

Might be similar/related to: https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/332

NSM 1.8.0
```
# smaps
7f6f5d22f000-7f6f6562f000 rw-s 00000000 00:07 20735                      socket:[20735]
Size:             135168 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:              135168 kB
Pss:              135168 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:    129516 kB
Private_Dirty:      5652 kB
Referenced:       135168 kB
Anonymous:             0 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
FilePmdMapped:         0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
Locked:                0 kB
THPeligible:    0
VmFlags: rd wr sh mr mw me ms mm 

# lsof
vpp_main   6800                     root  mem       REG                0,7                20735 socket:[20735]
vpp_main   6800                     root   13u     pack              20735       0t0        ALL type=SOCK_RAW
```

Before:
```
7f0655b5f000-7f0656f5f000 rw-s 00000000 00:08 134146836                  socket:[134146836]
Size:              20480 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:               20480 kB
Pss:               20480 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:     16384 kB
Private_Dirty:      4096 kB
Referenced:        20480 kB
Anonymous:             0 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
FilePmdMapped:         0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
Locked:                0 kB
THPeligible:    0
ProtectionKey:         0
VmFlags: rd wr sh mr mw me ms sd mm 

```

**Comment by glazychev-art** [comment]
@zolug 
Could you recheck the issue on the main branch?
We merged a couple of fixes with frame sizes.

**Comment by zolug** [comment]
> @zolug Could you recheck the issue on the main branch? We merged a couple of fixes with frame sizes.

@glazychev-art 
Thanks. Yesterday I checked https://github.com/networkservicemesh/cmd-forwarder-vpp/pull/847, and the memory usage went back to the legacy values. I will try to check the veth pair based changes as well asap.

**Comment by zolug** [comment]
Works as intended.

**Comment by glazychev-art** [comment]
@zolug 
Thanks!
Can we close the issue?

**Comment by zolug** [comment]
> @zolug Thanks! Can we close the issue?

Yes, thanks for the quick fix.
