### ISSUE TITLE
VPP neighbor table is not updated properly in case of IP or MAC address change

### ISSUE THREAD

**Issue by szvincze** [networkservicemesh/cmd-forwarder-vpp#853]
When we use an OVS interface on the host, the IP and MAC address can change at worker node restart.
In such cases it will not stored in VPP neighbor table which causes issues at restart (address resolution does not work).

It occurs with NSM version 1.6.2 and 1.8.0 too.

**Comment by ljkiraly** [comment]
Reproduction steps:

- run Kernel2Ethernet2Kernel example use-case in kind

- check that the ping works between NSC and NSE

- check the neighbor table inside vpp

```
kubectl get pods -o wide -n nsm-system -l app=forwarder-vpp
NAME                  READY   STATUS    RESTARTS      AGE   IP           NODE           NOMINATED NODE   READINESS GATES
forwarder-vpp-2g4dh   1/1     Running   1 (27m ago)   34m   172.18.0.3   kind-worker2   <none>           <none>
forwarder-vpp-stvwh   1/1     Running   1 (25m ago)   34m   172.18.0.2   kind-worker    <none>           <none>

kubectl exec -n nsm-system forwarder-vpp-2g4dh vppctl sh ip neighbor
    Time                       IP                    Flags      Ethernet              Interface       
      4.5853               172.18.0.1                  D    02:42:3e:b4:19:e3 host-eth0
      1.2279               172.18.0.2                  S    02:42:ac:12:00:02 host-eth0
      1.2277               172.18.0.4                  S    02:42:ac:12:00:04 host-eth0

```
- set the hardware address of the interface used for vxlan connection in kind-worker node

```
> docker exec kind-worker ip a s dev eth0
231: eth0@if232: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:12:00:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.18.0.2/16 brd 172.18.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fc00:f853:ccd:e793::2/64 scope global nodad 
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe12:2/64 scope link 
       valid_lft forever preferred_lft forever

> docker exec kind-worker ip link set dev eth0 addr 02:42:ac:12:00:22
> docker exec kind-worker ip link show dev eth0
231: eth0@if232: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether 02:42:ac:12:00:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
```

- restart the forwarder running in this worker node:

`> docker exec -it kind-worker pkill vpp
`
- check the neighbor table (remains unchanged)

```
kubectl exec -n nsm-system forwarder-vpp-2g4dh vppctl sh ip neighbor
    Time                       IP                    Flags      Ethernet              Interface       
      4.5853               172.18.0.1                  D    02:42:3e:b4:19:e3 host-eth0
      1.2279               172.18.0.2                  S    02:42:ac:12:00:02 host-eth0
      1.2277               172.18.0.4                  S    02:42:ac:12:00:04 host-eth0

```

- check that the ping does not work between NSC and NSE

- removing the old neighbor and adding back the right one to vpp by hand can solve the problem (after this the ping works again)

```
kubectl exec -n nsm-system forwarder-vpp-2g4dh vppctl ip neighbor del host-eth0 172.18.0.2 02:42:ac:12:00:02
kubectl exec -n nsm-system forwarder-vpp-2g4dh vppctl ip neighbor host-eth0 172.18.0.2 02:42:ac:12:00:22
kubectl exec -n nsm-system forwarder-vpp-2g4dh vppctl sh ip neighbor
 
    273.3889               172.18.0.1                  D    02:42:3e:b4:19:e3 host-eth0
    379.4712               172.18.0.2                  D    02:42:ac:12:00:22 host-eth0
    1.2277               172.18.0.4                  S    02:42:ac:12:00:04 host-eth0

```
What would be the side effect of setting dynamic neighbors (instead of static) at [interface creation](https://github.com/networkservicemesh/cmd-forwarder-vpp/blob/22ba8e6607075e7bcccdfc72df34145b74858729/internal/vppinit/vppinit.go#L250) when initializing the forwarder?

**Comment by glazychev-art** [comment]
@ljkiraly 
Thanks for the detailed steps!
Do dynamic neighbors help you?
I don't think there are any side effects. I tested it on a couple of clusters - everything works well

**Comment by ljkiraly** [comment]
@glazychev-art Yes, the dynamic neighbor setup helps. Thanks.

**Comment by zolug** [comment]
Hi @glazychev-art,

Could please explain, how VPP is supposed to learn neighbors?
Based on your linked PR vpp-forwarder on startup fetches the reachable neighbor's list at that time, and configures those as neighbors in VPP.
How else, can VPP learn about neighbors? (For example in case a new node is introduced into the system.)

Thanks in advance.

**Comment by glazychev-art** [comment]
Hi @zolug 
Good catch, thank you!

I think we can close this issue
