### ISSUE TITLE
Forwarder sometimes crashes with segmentation fault after restart

### ISSUE THREAD

**Issue by szvincze** [networkservicemesh/cmd-forwarder-vpp#953]
I tested several forwarder restarts sequentially and sometimes it thrown panic on a segmentation fault:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf23672]

goroutine 276 [running]:
github.com/networkservicemesh/sdk-vpp/pkg/networkservice/pinhole.tunnelIPSwIfIndex({0x147caf0, 0xc000986b10}, {0x7f7d585f7c18?, 0xc0000bf120}, {0xc00028bb00, 0x10, 0x10})
	/root/go/pkg/mod/github.com/networkservicemesh/sdk-vpp@v0.0.0-20231002104338-c5aa8c256465/pkg/networkservice/pinhole/common.go:210 +0x3d2
github.com/networkservicemesh/sdk-vpp/pkg/networkservice/pinhole.create({0x147caf0, 0xc000986b10}, {0x7f7d585f7c18, 0xc0000bf120}, {0xc00028bb00, 0x10, 0x10}, 0x12b5, {0xc00002a8a0, 0x15})
```
See the logs attached: [forwarder-restart-segfault.log](https://github.com/networkservicemesh/cmd-forwarder-vpp/files/12792993/forwarder-restart-segfault.log)

**Comment by denis-tingaikin** [comment]
@szvincze Nice catch! 

The panic should be fixed and now we need to check what happens next with the forwawrder.

Could you please re-test with the latest forwarder?

**Comment by denis-tingaikin** [comment]
Latest forwarder image is https://github.com/networkservicemesh/cmd-forwarder-vpp/pkgs/container/ci%2Fcmd-forwarder-vpp/133810960?tag=9d48b78

**Comment by szvincze** [comment]
I need some time to reconfigure my environment to use the latest image but will test it.

**Comment by szvincze** [comment]
I have been testing this image for a while. The panic haven't happened so far but haven't even seen the corresponding error message in the logs.

**Comment by denis-tingaikin** [comment]
That's good news. Could we close the ticket?

**Comment by szvincze** [comment]
I close it now. If something happen during the coming tests I can open another one.
