### ISSUE TITLE
Datapath healing does not work when host interface goes down and up again

### ISSUE THREAD

**Issue by szvincze** [networkservicemesh/cmd-forwarder-vpp#958]
During a test we set the host interface administrative down then up again within a second. The traffic immediately stops on the affected node and can only be recovered by restarting the forwarder on that node.

I attached the [forwarder-vpp.log](https://github.com/networkservicemesh/cmd-forwarder-vpp/files/12847532/forwarder-vpp-healing.log) and the [output](https://github.com/networkservicemesh/cmd-forwarder-vpp/files/12847541/vppctl-output.txt) of the `vppctl show interface` command. It seems the interfaces are deleted then re-created but cannot come up properly in an endless loop.

I managed to reproduce it in kind environment too in a basic setup, but instead of changing the administrative state of the host interface I just disconnected a kind-worker for a moment then connect it again. For example:
```
docker network disconnect kind kind-worker2
docker network connect kind kind-worker2
```
The same behavior was observed on NSM v1.11.0 and on previous versions before the release.

**Comment by szvincze** [comment]
Is there a document or presentation material that would explain how the interface and the related events are handled?

Based on our observation the changes of the admin/operational state of the host interface reflected immediately by the forwarder. So, it would be interesting to know how the detection works. Is it event driven or done by a detection mechanism?

**Comment by glazychev-art** [comment]
I don't think that 
```
docker network disconnect kind kind-worker2
docker network connect kind kind-worker2
```
is the same as up/down interface. I did that and I got:
before:
```
77: eth2@if78: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:12:00:05 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.18.0.5/16 brd 172.18.255.255 scope global eth2
       valid_lft forever preferred_lft forever
    inet6 fc00:f853:ccd:e793::5/64 scope global nodad 
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe12:5/64 scope link 
       valid_lft forever preferred_lft forever
```
after:
```
79: eth3@if80: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:12:00:05 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.18.0.5/16 brd 172.18.255.255 scope global eth3
       valid_lft forever preferred_lft forever
    inet6 fc00:f853:ccd:e793::5/64 scope global nodad 
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe12:5/64 scope link 
       valid_lft forever preferred_lft forever
```
This is **_not_** the same interface. It has different name and different ID.
I think this is the same as changing the NIC, but setting the same address.

I think these commands are more correct:
```
docker exec kind-worker ip link set eth0 down
docker exec kind-worker ip link set eth0 up
```

As for the problem, it looks like this is the same - https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/927
We found some bugs and are now preparing fixes

**Comment by szvincze** [comment]
That's very good news. Have you seen similar symptoms on the host interface like in case of #927?
I mean RX counters are not increasing or not printed out in `vppctl show interface`.

**Comment by glazychev-art** [comment]
Yes, I restarted the forwarders several times and the problem is reproduced.
But in fact, I see that TX is not increasing..

**Comment by NikitaSkrynnik** [comment]
Checked the setup several times and couldn't reproduce it
